In [1]:
import pandas as pd 
import numpy as np

In [2]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [5]:
date.sample(1)

           date  product_id  city_id  orders
825  2019-03-25        4691       14       1

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [24]:
#date['date_year'] = date['date'].dt.year
# date['date_m'] = date['date'].dt.month
# date['date_m_name'] = date['date'].dt.month_name()
# date['date_day'] = date['date'].dt.day
# date['date_day_ofweek'] = date['date'].dt.dayofweek
# date['date_day_name'] = date['date'].dt.day_name()
date['date_week_no'] = date['date'].dt.week

AttributeError: 'DatetimeProperties' object has no attribute 'week'

In [23]:
date.sample(3)

,date,product_id,city_id,orders,date_year,date_m,date_m_name,date_day,date_day_ofweek,date_day_name
69,2018-12-28,2652,18,84,2018,12,December,28,4,Friday
774,2019-08-17,2459,0,8,2019,8,August,17,5,Saturday
900,2018-10-09,6803,19,23,2018,10,October,9,1,Tuesday

In [26]:

# is weekend?

date['date_is_weekend'] = np.where(date['date_day_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_m,date_m_name,date_day,date_day_ofweek,date_day_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [27]:

date['date_week'] = date['date'].dt.week

date.drop(columns=['product_id','city_id','orders']).head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'

In [28]:

date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_m,date_m_name,date_day,date_day_ofweek,date_day_name,date_is_weekend,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [29]:

date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_m,date_m_name,date_day,date_day_ofweek,date_day_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [30]:

import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 1, 3, 10, 53, 45, 295379)

In [31]:

today - date['date']

0     2216 days 10:53:45.295379
1     2698 days 10:53:45.295379
2     2629 days 10:53:45.295379
3     2331 days 10:53:45.295379
4     2554 days 10:53:45.295379
                 ...
995   2644 days 10:53:45.295379
996   2585 days 10:53:45.295379
997   2433 days 10:53:45.295379
998   2498 days 10:53:45.295379
999   2272 days 10:53:45.295379
Name: date, Length: 1000, dtype: timedelta64[ns]

In [32]:

(today - date['date']).dt.days

0      2216
1      2698
2      2629
3      2331
4      2554
       ...
995    2644
996    2585
997    2433
998    2498
999    2272
Name: date, Length: 1000, dtype: int64

In [33]:
np.round((today -date['date']) / np.timedelta64(1, 'M'),0)

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

In [34]:

time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [35]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [36]:

time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [37]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [38]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [39]:

today - time['date']

0     4402 days 10:03:45.295379
1     4266 days 11:13:45.295379
2     4752 days 10:32:45.295379
3     4054 days 10:22:45.295379
4     4451 days 11:42:45.295379
                 ...
995   5041 days 10:03:45.295379
996   4362 days 11:39:45.295379
997   4827 days 11:16:45.295379
998   4943 days 11:19:45.295379
999   4215 days 11:28:45.295379
Name: date, Length: 1000, dtype: timedelta64[ns]